export const FETCH_GENRES_BEGIN = "FETCH_GENRES_BEGIN";
export const FETCH_GENRES_SUCCESS = "FETCH_GENRES_SUCCESS";
export const FETCH_GENRES_FAILURE = "FETCH_GENRES_FAILURE";

export const FETCH_GENRE_ARTISTS_BEGIN = "FETCH_GENRE_ARTISTS_BEGIN";
export const FETCH_GENRE_ARTISTS_SUCCESS = "FETCH_GENRE_ARTISTS_SUCCESS";
export const FETCH_GENRE_ARTISTS_FAILURE = "FETCH_GENRE_ARTISTS_FAILURE";
